### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by ubolonton** [TheBB/libegit2#1]
Build fails on macOS 0.13.4 (17E199).
Package manager is MacPorts.

This is the error:
```
[100%] Linking C shared library libegit2.dylib
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _git_path_iconv in libgit2.a(path.c.o)
  "_libiconv_close", referenced from:
      _git_path_iconv_clear in libgit2.a(path.c.o)
  "_libiconv_open", referenced from:
      _git_path_iconv_init_precompose in libgit2.a(path.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libegit2.dylib] Error 1
make[1]: *** [src/CMakeFiles/egit2.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by TheBB** [comment]
https://github.com/rust-lang/cargo/issues/1032 seems relevant.

Can you check where your libiconv is, if cmake can find it correctly and if it invokes linking with the right paths (`make VERBOSE=1`).

**Comment by ubolonton** [comment]
Thanks! I'll check that out.

**Comment by TheBB** [comment]
Try something like `cmake -DCMAKE_PREFIX_PATH=/opt/local ..`

**Comment by ubolonton** [comment]
That works.

Testing fails with this

```
Running tests...
Test project /Users/ubolonton/Programming/lib/libegit2/build
    Start 1: libegit2_repository
Process not started
 /Users/ubolonton/Programming/lib/libegit2/cask
[permission denied]
1/1 Test #1: libegit2_repository ..............***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
          1 - libegit2_repository (BAD_COMMAND)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by ubolonton** [comment]
Using `cask exec ert-runner` gives this error instead `Cannot open load file: No such file or directory, libegit2`.

**Comment by TheBB** [comment]
That's very strange. The load-path is tweaked in `test-helpers.el`, line 1, and there should be a `libegit.xyz` in the build directory, no?

**Comment by ubolonton** [comment]
Silly me. I should have remembered this. Shared libs in macOS has `.dylib` extension, while `module-file-suffix` is `".so"`. My own modules have build scripts that create `.so` symlink.

**Comment by ubolonton** [comment]
`make test` still doesn't work, but `cask exec ert-runner` works now, with 2 failed tests.

**Comment by ubolonton** [comment]
I think we should set up Travis integration for this now, to iterate faster. They support testing on mac OS.

Integration is pretty simple, like this: https://github.com/ubolonton/emacs-module-rs/blob/master/.travis.yml

**Comment by TheBB** [comment]
Yep, agree.

I thought Emacs would look for `.dylib` files by default on Mac.

**Comment by TheBB** [comment]
Looks like `/tmp` is a symlink to `/private/tmp`...

**Comment by TheBB** [comment]
Tests are passing on OSX and I've added the macports gotcha to the readme.

Thanks for helping with this. :-)

**Comment by ubolonton** [comment]
🎉

**Comment by Lord-Kamina** [comment]
I had this same issue; the problem is with cargo trying to use the macports (although probably same thing will happen with homebrew) instead of the system one. This happens when anything adds the package manager tree to the library/include search paths. I did many other patches as well (might eventually try to remove them one-by-one to see whether they're actually all needee or not but tbh building takes so long I'm not sure it's worth it). Common culprits seem to be curl and libgit2-sys as they depend on OpenSSL newer than what macOS ships by default. In my case I patched the libgit2-sys cmake modules to make sure it prefers the system libiconv, but I also set it so openssl-sys defaults to vendored; this avoids it trying to find OpenSSL in the macports prefix and then causing the libiconv issue. I'll post details at some point tomorrow when I gwt home most likely.

**Comment by s-kostyaev** [comment]
@TheBB for now on mac os build is broken. Instead of `libegit2.dylib` there is `libegit2.so`.

**Comment by TheBB** [comment]
https://github.com/magit/libegit2/blob/master/src/CMakeLists.txt#L6-L10

That was purposeful. From what I could see based on the Travis tests, Emacs on OSX looked for `.so` files, not `.dylib`, so I had to override the extension.

Has that changed?

**Comment by s-kostyaev** [comment]
> Emacs on OSX looked for .so files, not .dylib

This is not true. Maybe it's not true in emacs 27 only. But I have this issue.

**Comment by TheBB** [comment]
Could you PR a fix? I don't have an OSX computer so it's difficult for me to test. I assume safest would be to add a cmake directive to copy the generated file so there's both a `.so` and a `.dylib` present. In the linked file there's already one that copies the library to the parent dir, so you can see how it should look like.

**Comment by s-kostyaev** [comment]
I will try.
